
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bd-twitter-bot
spec:
  selector:
    matchLabels:
      app: bd-twitter-bot
  replicas: 1
  template:
    metadata:
      name: bl-twitter-bot-app
      labels:
        app: bd-twitter-bot
    spec:
      containers:
      - name: bd-twitter-bot
        image: hub.osrsbotdetector.com/bot-detector/bd-twitter-bot:latest
        imagePullPolicy: Always
        resources:
          limits:
            memory: "500Mi"
            cpu: "150m"
      imagePullSecrets:
      - name: regcred